version: "3.8"

services:
  database:
    image: postgres:16
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "db_admin", "-d", "db_name" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres_crypto:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_admin
      - POSTGRES_DB=db_name

  app:
    build: .
    container_name: bot
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      TELEBOT_TOKEN: ""
      COINMARKET_API: ""
      TELEBOT_STATS_CHANNEL: ""
      API_MAX_WORKERS: "10"
      DB_NAME: "db_name"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "db_admin"
      DB_PASSWORD: "db_password"